version: "3.3"
networks:
  queuest-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.7.0/24

services:
    postgres:
      container_name: "queuest-postgres"
      image: queuest/postgres
      build: setup/postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=master # user with superuser power
        - POSTGRES_PASSWORD=postgres # password for user 'master'
      expose:
        - "5432"
      ports:
        - "5432:5432"
      networks:
        queuest-network:
          ipv4_address: 172.19.7.103
    flyway:
      container_name: "queuest-flyway"
      image: flyway/flyway:7.2.0
      command: -url=jdbc:postgresql://172.19.7.103:5432/queuest -user=queuest -password=queuest -connectRetries=60 -ignoreMissingMigrations=true migrate
      volumes:
        - ./setup/postgres/flyway-migration:/flyway/sql/flyway-migration
        - ./setup/postgres/flyway-migration-dev:/flyway/sql/flyway-migration-dev
      networks:
        - queuest-network
      depends_on:
        - postgres
volumes:
  pgdata:
